name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Check build output (debug)
        run: |
          echo "=== Build output root ==="
          ls -la
          echo "=== .next directory ==="
          ls -la .next || echo ".next does not exist"
          echo "=== .next/standalone ==="
          ls -la .next/standalone || echo "standalone not found"
          echo "=== .next/static ==="
          ls -la .next/static || echo "static not found"

      - name: Prepare standalone output
        run: |
          mkdir -p app/.next
          cp -r .next/standalone/* app/
          cp -r .next/static app/.next/static
          cp server.js app/
          cp package.json app/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-001-step3-1-suzuyu-node-9
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

