name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Prepare build output
        run: |
          mkdir -p output/.next/static
          cp -r .next/standalone/* output/
          cp -r .next/static output/.next/
          [ -d public ] && cp -r public output/public
          cp -r node_modules output/node_modules
          cp package.json output/
          cp next.config.js output/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: output

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: output

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-001-step3-1-suzuyu-node-9
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./output
